export const profissionais = [
  {
    nome: "Dr. Emanuel Costa",
    especialidade: "Dermatologia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "250,00",
    horasDisponiveis: ["12:00", "14:00", "16:00"],
  },
  {
    nome: "Dra. Maria Silva",
    especialidade: "Cardiologia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "300,00",
    horasDisponiveis: ["10:00", "13:00", "15:00"],
  },
  {
    nome: "Dr. João Oliveira",
    especialidade: "Ortopedia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "200,00",
    horasDisponiveis: ["09:00", "11:00", "14:00"],
  },
  {
    nome: "Dra. Ana Pereira",
    especialidade: "Pediatria",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "180,00",
    horasDisponiveis: ["08:00", "10:00", "12:00"],
  },
  {
    nome: "Dr. Carlos Sousa",
    especialidade: "Ginecologia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "220,00",
    horasDisponiveis: ["13:00", "15:00", "17:00"],
  },
  {
    nome: "Dra. Helena Santos",
    especialidade: "Neurologia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "280,00",
    horasDisponiveis: ["09:00", "11:00", "13:00"],
  },
  {
    nome: "Dr. Roberto Lima",
    especialidade: "Psiquiatria",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "260,00",
    horasDisponiveis: ["10:00", "12:00", "14:00"],
  },
  {
    nome: "Dra. Isabel Ferreira",
    especialidade: "Oftalmologia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "240,00",
    horasDisponiveis: ["11:00", "13:00", "15:00"],
  },
  {
    nome: "Dr. Felipe Almeida",
    especialidade: "Cardiologia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "230,00",
    horasDisponiveis: ["08:00", "10:00", "12:00"],
  },
  {
    nome: "Dra. Carolina Mendes",
    especialidade: "Cardiologia",
    imagem: "../public/main-page/background-hero.jpg",
    valorConsulta: "270,00",
    horasDisponiveis: ["14:00", "16:00", "18:00"],
  },
];
